M.Talha Ramzan
===
2330-0141
===
BS AI
===

==============
=================
==================

**TASK :01 **
================
==================
======================

**Import Libraries**

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

**Dataset Load**

In [2]:
df = pd.read_csv("/content/car data.csv")

df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

**Dataset Information Check**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

**Car Name Column Remove**

In [4]:
df = df.drop("Car_Name", axis=1)

df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

**Categorical Data Encode**

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Fuel_Type"] = le.fit_transform(df["Fuel_Type"])
df["Seller_Type"] = le.fit_transform(df["Seller_Type"])
df["Transmission"] = le.fit_transform(df["Transmission"])

df.head()

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,3.35,5.59,27000,2,0,1,0
1,2013,4.75,9.54,43000,1,0,1,0
2,2017,7.25,9.85,6900,2,0,1,0
3,2011,2.85,4.15,5200,2,0,1,0
4,2014,4.60,6.87,42450,1,0,1,0

In [7]:
X = df.drop("Selling_Price", axis=1)
y = df["Selling_Price"]

print(X.head())
print(y.head())

   Year  Present_Price  Kms_Driven  Fuel_Type  Seller_Type  Transmission  \
0  2014           5.59       27000          2            0             1
1  2013           9.54       43000          1            0             1
2  2017           9.85        6900          2            0             1
3  2011           4.15        5200          2            0             1
4  2014           6.87       42450          1            0             1

   Owner
0      0
1      0
2      0
3      0
4      0
0    3.35
1    4.75
2    7.25
3    2.85
4    4.60
Name: Selling_Price, dtype: float64

**Train Test Split**

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

Training data shape: (240, 7)
Testing data shape: (61, 7)

**Feature Scaling**

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**ANN Model Build**

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(16, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(8, activation='relu'))
model.add(Dense(1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

**Compile Model (MAE Loss)**

In [11]:
model.compile(
    optimizer='adam',
    loss='mae',
    metrics=['mae']
)

**Train Model**

In [12]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 4.6940 - mae: 4.6940 - val_loss: 5.8094 - val_mae: 5.8094
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.2838 - mae: 4.2838 - val_loss: 5.6294 - val_mae: 5.6294
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.5251 - mae: 4.5251 - val_loss: 5.4765 - val_mae: 5.4765
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.1534 - mae: 5.1534 - val_loss: 5.3389 - val_mae: 5.3389
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.4061 - mae: 4.4061 - val_loss: 5.2141 - val_mae: 5.2141
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.1842 - mae: 4.1842 - val_loss: 5.1088 - val_mae: 5.1088
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.3583 - mae: 4.3583 - val_loss: 5.0099 - val_mae: 5.0099
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0078 - mae: 4.0078 - val_loss: 4.9277 - val_mae: 4.9277
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.1111 - mae: 4.1111 - val_loss: 4.8606 - val_mae: 4.8606
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.3889 - mae: 4.3889 - val_loss: 4.7972 - val_mae: 4.7972
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.2890 - mae: 4.2890 - val_loss: 4.7447 - val_mae: 4.7447
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.4874 - mae: 3.4874 - val_loss: 4.6924 - val_mae: 4.6924
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.9246 - mae: 3.9246 - val_loss: 4.6346 - val_mae: 4.6346
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.4669 - mae: 3.4669 - val_loss: 4.5720 - val_mae: 4.5720
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.3070 - mae: 4.3070 - val_loss: 4.5027 - val_mae: 4.5027
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0919 - mae: 4.0919 - val_loss: 4.4273 - val_mae: 4.4273
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.2873 - mae: 4.2873 - val_loss: 4.3392 - val_mae: 4.3392
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.7470 - mae: 3.7470 - val_loss: 4.2417 - val_mae: 4.2417
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.6344 - mae: 3.6344 - val_loss: 4.1330 - val_mae: 4.1330
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0513 - mae: 4.0513 - val_loss: 4.0123 - val_mae: 4.0123
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.3801 - mae: 3.3801 - val_loss: 3.8767 - val_mae: 3.8767
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.5329 - mae: 3.5329 - val_loss: 3.7313 - val_mae: 3.7313
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.2760 - mae: 3.2760 - val_loss: 3.5669 - val_mae: 3.5669
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8923 - mae: 2.8923 - val_loss: 3.3877 - val_mae: 3.3877
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.5287 - mae: 2.5287 - val_loss: 3.2131 - val_mae: 3.2131
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.6124 - mae: 2.6124 - val_loss: 3.0238 - val_mae: 3.0238
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9667 - mae: 2.9667 - val_loss: 2.8464 - val_mae: 2.8464
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.3904 - mae: 2.3904 - val_loss: 2.6626 - val_mae: 2.6626
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8476 - mae: 1.8476 - val_loss: 2.4916 - val_mae: 2.4916
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.9006 - mae: 1.9006 - val_loss: 2.3196 - val_mae: 2.3196
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.1669 - mae: 2.1669 - val_loss: 2.1782 - val_mae: 2.1782
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.5904 - mae: 1.5904 - val_loss: 2.0743 - val_mae: 2.0743
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.6346 - mae: 1.6346 - val_loss: 1.9810 - val_mae: 1.9810
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.6141 - mae: 1.6141 - val_loss: 1.8760 - val_mae: 1.8760
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7081 - mae: 1.7081 - val_loss: 1.7792 - val_mae: 1.7792
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7539 - mae: 1.7539 - val_loss: 1.6888 - val_mae: 1.6888
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3206 - mae: 1.3206 - val_loss: 1.6111 - val_mae: 1.6111
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3548 - mae: 1.3548 - val_loss: 1.5349 - val_mae: 1.5349
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4337 - mae: 1.4337 - val_loss: 1.4414 - val_mae: 1.4414
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1628 - mae: 1.1628 - val_loss: 1.3432 - val_mae: 1.3432
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3828 - mae: 1.3828 - val_loss: 1.2617 - val_mae: 1.2617
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9973 - mae: 0.9973 - val_loss: 1.1846 - val_mae: 1.1846
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0821 - mae: 1.0821 - val_loss: 1.1063 - val_mae: 1.1063
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9241 - mae: 0.9241 - val_loss: 1.0519 - val_mae: 1.0519
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0654 - mae: 1.0654 - val_loss: 0.9884 - val_mae: 0.9884
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2072 - mae: 1.2072 - val_loss: 0.9616 - val_mae: 0.9616
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0222 - mae: 1.0222 - val_loss: 0.9188 - val_mae: 0.9188
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9997 - mae: 0.9997 - val_loss: 0.8909 - val_mae: 0.8909
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8183 - mae: 0.8183 - val_loss: 0.8734 - val_mae: 0.8734
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8035 - mae: 0.8035 - val_loss: 0.8639 - val_mae: 0.8639
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8056 - mae: 0.8056 - val_loss: 0.8418 - val_mae: 0.8418
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7542 - mae: 0.7542 - val_loss: 0.8392 - val_mae: 0.8392
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9408 - mae: 0.9408 - val_loss: 0.8081 - val_mae: 0.8081
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9577 - mae: 0.9577 - val_loss: 0.7919 - val_mae: 0.7919
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8179 - mae: 0.8179 - val_loss: 0.7767 - val_mae: 0.7767
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8279 - mae: 0.8279 - val_loss: 0.7443 - val_mae: 0.7443
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7906 - mae: 0.7906 - val_loss: 0.7445 - val_mae: 0.7445
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7370 - mae: 0.7370 - val_loss: 0.7166 - val_mae: 0.7166
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7014 - mae: 0.7014 - val_loss: 0.7254 - val_mae: 0.7254
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7148 - mae: 0.7148 - val_loss: 0.7049 - val_mae: 0.7049
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6142 - mae: 0.6142 - val_loss: 0.7026 - val_mae: 0.7026
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6542 - mae: 0.6542 - val_loss: 0.6924 - val_mae: 0.6924
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7376 - mae: 0.7376 - val_loss: 0.6891 - val_mae: 0.6891
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7871 - mae: 0.7871 - val_loss: 0.6804 - val_mae: 0.6804
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6141 - mae: 0.6141 - val_loss: 0.6814 - val_mae: 0.6814
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7008 - mae: 0.7008 - val_loss: 0.6861 - val_mae: 0.6861
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6637 - mae: 0.6637 - val_loss: 0.6825 - val_mae: 0.6825
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6562 - mae: 0.6562 - val_loss: 0.6858 - val_mae: 0.6858
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7304 - mae: 0.7304 - val_loss: 0.6809 - val_mae: 0.6809
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6319 - mae: 0.6319 - val_loss: 0.6985 - val_mae: 0.6985
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6790 - mae: 0.6790 - val_loss: 0.6718 - val_mae: 0.6718
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7422 - mae: 0.7422 - val_loss: 0.6893 - val_mae: 0.6893
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6089 - mae: 0.6089 - val_loss: 0.6914 - val_mae: 0.6914
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7247 - mae: 0.7247 - val_loss: 0.6942 - val_mae: 0.6942
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6186 - mae: 0.6186 - val_loss: 0.6939 - val_mae: 0.6939
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7769 - mae: 0.7769 - val_loss: 0.6755 - val_mae: 0.6755
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6949 - mae: 0.6949 - val_loss: 0.7053 - val_mae: 0.7053
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7070 - mae: 0.7070 - val_loss: 0.6778 - val_mae: 0.6778
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6783 - mae: 0.6783 - val_loss: 0.6974 - val_mae: 0.6974
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.7548 - mae: 0.7548 - val_loss: 0.7044 - val_mae: 0.7044
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6814 - mae: 0.6814 - val_loss: 0.7012 - val_mae: 0.7012
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6815 - mae: 0.6815 - val_loss: 0.6981 - val_mae: 0.6981
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6826 - mae: 0.6826 - val_loss: 0.7057 - val_mae: 0.7057
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5923 - mae: 0.5923 - val_loss: 0.7013 - val_mae: 0.7013
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5944 - mae: 0.5944 - val_loss: 0.7076 - val_mae: 0.7076
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6385 - mae: 0.6385 - val_loss: 0.7160 - val_mae: 0.7160
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5890 - mae: 0.5890 - val_loss: 0.6934 - val_mae: 0.6934
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5728 - mae: 0.5728 - val_loss: 0.7249 - val_mae: 0.7249
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.4965 - mae: 0.4965 - val_loss: 0.7230 - val_mae: 0.7230
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5172 - mae: 0.5172 - val_loss: 0.7159 - val_mae: 0.7159
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5040 - mae: 0.5040 - val_loss: 0.7209 - val_mae: 0.7209
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5754 - mae: 0.5754 - val_loss: 0.7082 - val_mae: 0.7082
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5370 - mae: 0.5370 - val_loss: 0.7085 - val_mae: 0.7085
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5241 - mae: 0.5241 - val_loss: 0.7114 - val_mae: 0.7114
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6192 - mae: 0.6192 - val_loss: 0.7199 - val_mae: 0.7199
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5257 - mae: 0.5257 - val_loss: 0.7215 - val_mae: 0.7215
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6233 - mae: 0.6233 - val_loss: 0.7164 - val_mae: 0.7164
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.5615 - mae: 0.5615 - val_loss: 0.7266 - val_mae: 0.7266
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5855 - mae: 0.5855 - val_loss: 0.7146 - val_mae: 0.7146
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5098 - mae: 0.5098 - val_loss: 0.7271 - val_mae: 0.7271

**Evaluate Model**

In [13]:
loss, mae = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test MAE:", mae)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.5602 - mae: 0.5602
Test Loss: 0.6168501973152161
Test MAE: 0.6168501973152161

**ANN Model with MSE Loss**

In [14]:
model2 = Sequential()

model2.add(Dense(16, activation='relu', input_dim=X_train.shape[1]))
model2.add(Dense(8, activation='relu'))
model2.add(Dense(1))

model2.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mse']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

**Train MSE Model**

In [15]:
history2 = model2.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 48.8215 - mse: 48.8215 - val_loss: 47.9191 - val_mse: 47.9191
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 47.7921 - mse: 47.7921 - val_loss: 46.2773 - val_mse: 46.2773
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 62.0971 - mse: 62.0971 - val_loss: 44.6826 - val_mse: 44.6826
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 52.8241 - mse: 52.8241 - val_loss: 43.1160 - val_mse: 43.1160
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 42.0432 - mse: 42.0432 - val_loss: 41.3727 - val_mse: 41.3727
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 52.1870 - mse: 52.1870 - val_loss: 39.4246 - val_mse: 39.4246
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 38.9677 - mse: 38.9677 - val_loss: 37.3485 - val_mse: 37.3485
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 37.8200 - mse: 37.8200 - val_loss: 35.2032 - val_mse: 35.2032
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 34.6750 - mse: 34.6750 - val_loss: 33.0856 - val_mse: 33.0856
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 38.6337 - mse: 38.6337 - val_loss: 30.9869 - val_mse: 30.9869
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 36.3266 - mse: 36.3266 - val_loss: 28.8314 - val_mse: 28.8314
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30.6575 - mse: 30.6575 - val_loss: 26.7451 - val_mse: 26.7451
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 24.4983 - mse: 24.4983 - val_loss: 24.7221 - val_mse: 24.7221
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 32.5297 - mse: 32.5297 - val_loss: 22.5725 - val_mse: 22.5725
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 29.5250 - mse: 29.5250 - val_loss: 20.7220 - val_mse: 20.7220
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 42.8180 - mse: 42.8180 - val_loss: 18.7985 - val_mse: 18.7985
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.0252 - mse: 25.0252 - val_loss: 17.0577 - val_mse: 17.0577
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 32.0788 - mse: 32.0788 - val_loss: 15.5813 - val_mse: 15.5813
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.5977 - mse: 21.5977 - val_loss: 14.2562 - val_mse: 14.2562
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.3464 - mse: 12.3464 - val_loss: 13.0562 - val_mse: 13.0562
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.7995 - mse: 13.7995 - val_loss: 11.9659 - val_mse: 11.9659
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.8506 - mse: 17.8506 - val_loss: 10.8659 - val_mse: 10.8659
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.0483 - mse: 12.0483 - val_loss: 9.9912 - val_mse: 9.9912
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.1932 - mse: 9.1932 - val_loss: 9.2004 - val_mse: 9.2004
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.9809 - mse: 12.9809 - val_loss: 8.3465 - val_mse: 8.3465
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.8132 - mse: 13.8132 - val_loss: 7.5287 - val_mse: 7.5287
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18.3473 - mse: 18.3473 - val_loss: 6.7976 - val_mse: 6.7976
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.3357 - mse: 14.3357 - val_loss: 6.2338 - val_mse: 6.2338
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.6147 - mse: 11.6147 - val_loss: 5.6058 - val_mse: 5.6058
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9883 - mse: 8.9883 - val_loss: 5.1477 - val_mse: 5.1477
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.1937 - mse: 13.1937 - val_loss: 4.7207 - val_mse: 4.7207
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4460 - mse: 8.4460 - val_loss: 4.3071 - val_mse: 4.3071
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.8498 - mse: 6.8498 - val_loss: 3.9712 - val_mse: 3.9712
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.4015 - mse: 5.4015 - val_loss: 3.6524 - val_mse: 3.6524
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.5903 - mse: 3.5903 - val_loss: 3.4315 - val_mse: 3.4315
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.0436 - mse: 5.0436 - val_loss: 3.0826 - val_mse: 3.0826
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3754 - mse: 7.3754 - val_loss: 2.8486 - val_mse: 2.8486
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.7763 - mse: 4.7763 - val_loss: 2.7090 - val_mse: 2.7090
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.7096 - mse: 3.7096 - val_loss: 2.5912 - val_mse: 2.5912
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.0879 - mse: 3.0879 - val_loss: 2.4387 - val_mse: 2.4387
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.4402 - mse: 4.4402 - val_loss: 2.3156 - val_mse: 2.3156
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7930 - mse: 2.7930 - val_loss: 2.2746 - val_mse: 2.2746
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.4323 - mse: 4.4323 - val_loss: 2.1883 - val_mse: 2.1883
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.9272 - mse: 3.9272 - val_loss: 2.0822 - val_mse: 2.0822
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4828 - mse: 2.4828 - val_loss: 2.0334 - val_mse: 2.0334
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9075 - mse: 2.9075 - val_loss: 1.9452 - val_mse: 1.9452
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.1364 - mse: 3.1364 - val_loss: 1.8951 - val_mse: 1.8951
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8949 - mse: 2.8949 - val_loss: 1.8724 - val_mse: 1.8724
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3765 - mse: 3.3765 - val_loss: 1.8094 - val_mse: 1.8094
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.0246 - mse: 3.0246 - val_loss: 1.7796 - val_mse: 1.7796
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7989 - mse: 1.7989 - val_loss: 1.7577 - val_mse: 1.7577
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.4238 - mse: 2.4238 - val_loss: 1.7101 - val_mse: 1.7101
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.1301 - mse: 3.1301 - val_loss: 1.6868 - val_mse: 1.6868
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8239 - mse: 1.8239 - val_loss: 1.6618 - val_mse: 1.6618
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4189 - mse: 1.4189 - val_loss: 1.6555 - val_mse: 1.6555
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3886 - mse: 1.3886 - val_loss: 1.6529 - val_mse: 1.6529
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.3877 - mse: 2.3877 - val_loss: 1.6098 - val_mse: 1.6098
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3294 - mse: 1.3294 - val_loss: 1.5900 - val_mse: 1.5900
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5205 - mse: 1.5205 - val_loss: 1.5753 - val_mse: 1.5753
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4711 - mse: 1.4711 - val_loss: 1.5604 - val_mse: 1.5604
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8619 - mse: 1.8619 - val_loss: 1.5195 - val_mse: 1.5195
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.6462 - mse: 1.6462 - val_loss: 1.5199 - val_mse: 1.5199
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1753 - mse: 1.1753 - val_loss: 1.5237 - val_mse: 1.5237
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6783 - mse: 1.6783 - val_loss: 1.5084 - val_mse: 1.5084
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3853 - mse: 1.3853 - val_loss: 1.4983 - val_mse: 1.4983
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5207 - mse: 1.5207 - val_loss: 1.4685 - val_mse: 1.4685
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3275 - mse: 1.3275 - val_loss: 1.4757 - val_mse: 1.4757
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3925 - mse: 1.3925 - val_loss: 1.4765 - val_mse: 1.4765
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1370 - mse: 1.1370 - val_loss: 1.4497 - val_mse: 1.4497
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4233 - mse: 1.4233 - val_loss: 1.4202 - val_mse: 1.4202
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1771 - mse: 1.1771 - val_loss: 1.4374 - val_mse: 1.4374
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.4888 - mse: 1.4888 - val_loss: 1.3992 - val_mse: 1.3992
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3943 - mse: 1.3943 - val_loss: 1.4374 - val_mse: 1.4374
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3081 - mse: 1.3081 - val_loss: 1.4426 - val_mse: 1.4426
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.1724 - mse: 1.1724 - val_loss: 1.4053 - val_mse: 1.4053
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - loss: 1.8057 - mse: 1.8057 - val_loss: 1.3852 - val_mse: 1.3852
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 1.2659 - mse: 1.2659 - val_loss: 1.3938 - val_mse: 1.3938
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0910 - mse: 1.0910 - val_loss: 1.3666 - val_mse: 1.3666
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.5592 - mse: 1.5592 - val_loss: 1.3531 - val_mse: 1.3531
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1755 - mse: 1.1755 - val_loss: 1.3989 - val_mse: 1.3989
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0382 - mse: 1.0382 - val_loss: 1.3693 - val_mse: 1.3693
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9108 - mse: 0.9108 - val_loss: 1.3935 - val_mse: 1.3935
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0765 - mse: 1.0765 - val_loss: 1.3789 - val_mse: 1.3789
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2426 - mse: 1.2426 - val_loss: 1.3818 - val_mse: 1.3818
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.6181 - mse: 1.6181 - val_loss: 1.3192 - val_mse: 1.3192
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0866 - mse: 1.0866 - val_loss: 1.3555 - val_mse: 1.3555
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9147 - mse: 0.9147 - val_loss: 1.3484 - val_mse: 1.3484
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0758 - mse: 1.0758 - val_loss: 1.3748 - val_mse: 1.3748
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8069 - mse: 0.8069 - val_loss: 1.3351 - val_mse: 1.3351
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0577 - mse: 1.0577 - val_loss: 1.3260 - val_mse: 1.3260
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9931 - mse: 0.9931 - val_loss: 1.3379 - val_mse: 1.3379
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0424 - mse: 1.0424 - val_loss: 1.3266 - val_mse: 1.3266
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9969 - mse: 0.9969 - val_loss: 1.3266 - val_mse: 1.3266
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8870 - mse: 0.8870 - val_loss: 1.3218 - val_mse: 1.3218
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4162 - mse: 1.4162 - val_loss: 1.3181 - val_mse: 1.3181
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8436 - mse: 0.8436 - val_loss: 1.3164 - val_mse: 1.3164
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3361 - mse: 1.3361 - val_loss: 1.3224 - val_mse: 1.3224
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8191 - mse: 0.8191 - val_loss: 1.3154 - val_mse: 1.3154
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8216 - mse: 0.8216 - val_loss: 1.3156 - val_mse: 1.3156
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3097 - mse: 1.3097 - val_loss: 1.3023 - val_mse: 1.3023

**Evaluate MSE Model**

In [16]:
loss, mse = model2.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test MSE:", mse)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.6753 - mse: 0.6753
Test Loss: 0.6668959856033325
Test MSE: 0.6668959856033325

======================================
=======================================
=======================================

**Task 2 — Spam Email Classification**
==================================
======================================
=======================================

**Import Libraries**

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

**Load Dataset**

In [27]:
df = pd.read_csv("/content/spam.csv", sep='\t', encoding='latin-1', on_bad_lines='skip')

df.head()

   Type                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [30]:
df.columns = df.columns.str.strip()


df = df.rename(columns={'Type': 'Label', 'Message': 'Message'})

df.head()

  Label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [31]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Label'] = le.fit_transform(df['Label'])

df.head()

   Label                                            Message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X = cv.fit_transform(df['Message']).toarray()
y = df['Label']

print("Feature matrix shape:", X.shape)
print("First 5 labels:", y[:5])

Feature matrix shape: (656, 2558)
First 5 labels: 0    0
1    0
2    1
3    0
4    0
Name: Label, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

Training shape: (524, 2558)
Testing shape: (132, 2558)

In [34]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(16, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [35]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [36]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=16,
    validation_split=0.2
)

Epoch 1/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.5317 - loss: 0.6922 - val_accuracy: 0.8571 - val_loss: 0.6373
Epoch 2/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9054 - loss: 0.5900 - val_accuracy: 0.8571 - val_loss: 0.5299
Epoch 3/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9022 - loss: 0.4443 - val_accuracy: 0.8762 - val_loss: 0.4284
Epoch 4/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9473 - loss: 0.2972 - val_accuracy: 0.8952 - val_loss: 0.3507
Epoch 5/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9781 - loss: 0.1961 - val_accuracy: 0.9143 - val_loss: 0.3011
Epoch 6/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9856 - loss: 0.1365 - val_accuracy: 0.9333 - val_loss: 0.2750
Epoch 7/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9896 - loss: 0.0854 - val_accuracy: 0.9333 - val_loss: 0.2613
Epoch 8/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9985 - loss: 0.0473 - val_accuracy: 0.9333 - val_loss: 0.2568
Epoch 9/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0324 - val_accuracy: 0.9429 - val_loss: 0.2536
Epoch 10/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0283 - val_accuracy: 0.9524 - val_loss: 0.2586
Epoch 11/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0185 - val_accuracy: 0.9524 - val_loss: 0.2638
Epoch 12/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0156 - val_accuracy: 0.9524 - val_loss: 0.2706
Epoch 13/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0114 - val_accuracy: 0.9524 - val_loss: 0.2743
Epoch 14/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0116 - val_accuracy: 0.9524 - val_loss: 0.2807
Epoch 15/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0086 - val_accuracy: 0.9524 - val_loss: 0.2864
Epoch 16/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0069 - val_accuracy: 0.9524 - val_loss: 0.2887
Epoch 17/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0068 - val_accuracy: 0.9524 - val_loss: 0.2926
Epoch 18/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0050 - val_accuracy: 0.9524 - val_loss: 0.2972
Epoch 19/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0042 - val_accuracy: 0.9524 - val_loss: 0.3013
Epoch 20/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.9524 - val_loss: 0.3060

In [37]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8971 - loss: 0.3715
Test Loss: 0.30840426683425903
Test Accuracy: 0.9166666865348816